name: Render Video

on:
  workflow_dispatch:
    inputs:
      text:
        description: 'Text for the video'
        required: true

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Render video
        run: npm run render src/components/TextVideo.tsx out/video.mp4 --props='{"text":"${{ github.event.inputs.text }}"}'
        
      - name: Upload video
        uses: actions/upload-artifact@v2
        with:
          name: rendered-video
          path: out/video.mp4